opt_in_rules:
  - multiline_parameters
  - multiline_arguments
disabled_rules:
  - opening_brace
line_length:
  warning: 150
  error: 200
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true
identifier_name:
  min_length:
    error: 3
  max_length:
    warning: 40
    error: 50
  excluded:
    - c
    - i
    - j
    - k
    - p
    - q
    - x
    - y
    - z
    - ok
    - to
    - id
function_body_length:
  warning: 300
  error: 500
function_parameter_count:
  warning: 6
  error: 8
type_body_length:
  warning: 300
  error: 700
file_length:
  warning: 1000
  error: 1500
  ignore_comment_only_lines: true
cyclomatic_complexity:
  warning: 30
  error: 50
reporter: "xcode"
